---
sidebar: sidebar
permalink: concept-licensing.html
keywords: freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go
summary: Several licensing options are available for Cloud Volumes ONTAP. Each option enables you to choose a configuration that meets your needs.
---

= Cloud Volumes ONTAP licensing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Several licensing options are available for Cloud Volumes ONTAP. Each option enables you to choose a consumption model that meets your needs.

== Licensing overview

The following licensing options are available for new customers.

Freemium offering::
Free of charge up to 500 GiB of provisioned capacity without purchasing a license or contract. Includes limited support.

Essentials package::
Pay by capacity for Cloud Volumes ONTAP in a number of different configurations.

Professional package::
Pay by capacity for any type of Cloud Volumes ONTAP configuration. Includes unlimited backups with Cloud Backup.

Keystone Flex Subscription::
A pay-as-you-grow subscription-based service that delivers a seamless hybrid cloud experience for HA pairs.

The previous by-node licensing model remains available for existing customers who have already purchased a license or who have an active marketplace subscription.

The following sections provide more details about each of these options.

== Freemium offering

Provides all Cloud Volumes ONTAP features free of charge from NetApp (cloud provider charges still apply).

* No license or contract is needed.
* Support from NetApp is not included.
* You're limited to 500 GiB of provisioned capacity per Cloud Volumes ONTAP system.
* You can use up to 10 Cloud Volumes ONTAP systems with the Freemium offering per NetApp account, in any cloud provider.
* If the provisioned capacity for a Cloud Volumes ONTAP system exceeds 500 GiB, Cloud Manager converts the system to the Essentials package (capacity-based licensing).
+
Any other systems that have less than 500 GiB of provisioned capacity stay on Freemium (as long as they were deployed using the Freemium offering).

Learn how to get started with the Freemium offering:

ifdef::aws[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in AWS]
endif::aws[]
ifdef::azure[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in Azure]
endif::azure[]
ifdef::gcp[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in Google Cloud]
endif::gcp[]

== Capacity-based licensing packages

Capacity-based licensing enables you to pay for Cloud Volumes ONTAP per TiB of capacity. The license is associated with your NetApp account and enables you to charge multiple systems against the license, as long as enough capacity is available through the license.

For example, you could purchase a single 20 TiB license, deploy four Cloud Volumes ONTAP systems, and then allocate a 5 TiB volume to each system, for a total of 20 TiB. The capacity is available to the volumes on each Cloud Volumes ONTAP system deployed in that account.

Capacity-based licensing is available in the form of a _package_. When you deploy a Cloud Volumes ONTAP system, you can choose the _Essentials_ package or the _Professional_ package.

Essentials package::
* Choose your Cloud Volumes ONTAP configuration:
** A single node or HA system
** File and block storage or secondary data for disaster recovery (DR)
* Add on any of NetApp's cloud data services at extra cost

Professional package::
* Provides licensing for any Cloud Volumes ONTAP configuration (single node or HA with any storage type)
* Includes volume backups using Cloud Backup (only for volumes charged against this license)
* Add on any of NetApp's cloud data services at extra cost

=== Consumption models

The Essentials and Professional packages are available with the following consumption models:

* A license (BYOL) purchased from NetApp that can be used to deploy Cloud Volumes ONTAP in any cloud provider.
+
The license is not restricted to a single cloud provider.

* An hourly subscription (PAYGO) from your cloud provider's marketplace.

* An annual contract from your cloud provider's marketplace.

Note the following:

* If you purchase a license from NetApp (BYOL), you also need to subscribe to the PAYGO offering from your cloud provider's marketplace.
+
Your license is always charged first, but you'll be charged from the hourly rate in the marketplace in these cases:

** If you exceed your licensed capacity
** If the term of your license expires

* If you have an annual contract from a marketplace, _all_ Cloud Volumes ONTAP systems that you deploy are charged against that contract. You can't mix and match an annual marketplace contract with BYOL.

=== Pricing

For details about pricing, go to https://cloud.netapp.com/ontap-cloud[NetApp Cloud Central^].

=== Free trials

A 30-day free trial is available from the pay-as-you-go subscription in your cloud provider's marketplace. The free trial includes Cloud Volumes ONTAP and Cloud Backup. The trial starts when you subscribe to the offering in the marketplace.

There are no instance or capacity limitations. You can deploy as many Cloud Volumes ONTAP systems as you'd like and allocate as much capacity as needed, free of charge for 30 days. The free trial automatically converts to a paid hourly subscription after 30 days.

There are no hourly software license charges for Cloud Volumes ONTAP, but infrastructure charges from your cloud provider still apply.

=== Supported configurations

Capacity-based licensing packages are available with Cloud Volumes ONTAP 9.7 and later.

=== Capacity limit

With this licensing model, each individual Cloud Volumes ONTAP system supports up to 2 PiB of capacity through disks and tiering to object storage.

There is no maximum capacity limitation when it comes to the license itself.

=== Notes about charging

* If you exceed your BYOL capacity or if your license expires, you'll be charged for overages at the hourly rate based on your marketplace subscription.

* For each package, there is a minimum 4 TiB capacity charge. Any Cloud Volumes ONTAP instance that has less than 4 TiB of capacity will be charged at a rate of 4 TiB.

* There are no extra licensing costs for additional data-serving storage VMs (SVMs), but there is a 4 TiB minimum capacity charge per data-serving SVM.

* Disaster recovery SVMs are charged according to the provisioned capacity.

* For HA pairs, you're only charged for the provisioned capacity on a node. You aren't charged for data that is synchronously mirrored to the partner node.

* You won't be charged for the capacity used by FlexClone volumes.

* Source and destination FlexCache volumes are considered primary data and charged according to the provisioned space.

=== How to get started

Learn how to get started with capacity-based licensing:

ifdef::aws[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in AWS]
endif::aws[]
ifdef::azure[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in Azure]
endif::azure[]
ifdef::gcp[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in Google Cloud]
endif::gcp[]

== Keystone Flex Subscription

A pay-as-you-grow subscription-based service that delivers a seamless hybrid cloud experience for those preferring OpEx consumption models to upfront CapEx or leasing.

Charging is based on the size of your committed capacity for one or more Cloud Volumes ONTAP HA pairs in your Keystone Flex Subscription.

The provisioned capacity for each volume is aggregated and compared to the committed capacity on your Keystone Flex Subscription periodically, and any overages are charged as burst on your Keystone Flex Subscription.

https://www.netapp.com/services/subscriptions/keystone/flex-subscription/[Learn more about Keystone Flex Subscriptions^].

=== Supported configurations

Keystone Flex Subscriptions are supported with HA pairs. This licensing option isn't supported with single node systems at this time.

=== Capacity limit

Each individual Cloud Volumes ONTAP system supports up to 2 PiB of capacity through disks and tiering to object storage.

=== How to get started

Learn how to get started with a Keystone Flex Subscription:

ifdef::aws[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in AWS]
endif::aws[]
ifdef::azure[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in Azure]
endif::azure[]
ifdef::gcp[]
* link:task-set-up-licensing-aws.html[Set up licensing for Cloud Volumes ONTAP in Google Cloud]
endif::gcp[]

== Node-based licensing

Node-based licensing is the previous generation licensing model that enabled you to license Cloud Volumes ONTAP by node. This licensing model is not available for new customers and no free trials are available. By-node charging has been replaced with the by-capacity charging methods described above.

Node-based licensing is still available for existing customers:

* If you have an active license, BYOL is available for license renewals only.
* If you have an active marketplace subscription, charging is still available through that subscription.

== License conversions

Converting an existing Cloud Volumes ONTAP system to another licensing method isn't supported. The three current licensing methods are capacity-based licensing, Keystone Flex Subscriptions, and node-based licensing. For example, you can't convert a system from node-based licensing to capacity-based licensing (and vice versa).

If you want to transition to another licensing method, you can purchase a license, deploy a new Cloud Volumes ONTAP system using that license, and then replicate the data to that new system.

== Max number of systems

The maximum number of Cloud Volumes ONTAP systems is limited to 20 per NetApp account, regardless of the licensing model in use.

A _system_ is either an HA pair or a single node system. For example, if you have two Cloud Volumes ONTAP HA pairs and two single node systems, you'd have a total of 4 systems, with room for 16 additional systems in your account.

If you have questions, reach out to your account rep or sales team.

https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html[Learn more about NetApp accounts^].
