---
sidebar: sidebar
permalink: concept-performance.html
keywords: performance, technical report, TR, workload, cpu
summary: You can review performance results to help you decide which workloads are appropriate for Cloud Volumes ONTAP.
---

= Performance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can review performance results to help you decide which workloads are appropriate for Cloud Volumes ONTAP.

== Performance technical reports

ifdef::aws[]
* Cloud Volumes ONTAP for AWS
+
link:https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf[NetApp Technical Report 4383: Performance Characterization of Cloud Volumes ONTAP in Amazon Web Services with Application Workloads^]
endif::aws[]

ifdef::azure[]
* Cloud Volumes ONTAP for Microsoft Azure
+
link:https://www.netapp.com/pdf.html?item=/media/9089-tr-4671pdf.pdf[NetApp Technical Report 4671: Performance Characterization of Cloud Volumes ONTAP in Azure with Application Workloads^]
endif::azure[]

ifdef::gcp[]
* Cloud Volumes ONTAP for Google Cloud
+
link:https://www.netapp.com/pdf.html?item=/media/9090-tr4816pdf.pdf[NetApp Technical Report 4816: Performance Characterization of Cloud Volumes ONTAP for Google Cloud^]
endif::gcp[]

== CPU performance

Cloud Volumes ONTAP nodes show as highly utilized (over 90%) from your cloud provider's monitoring tools. This is because ONTAP reserves all vCPUs presented to the virtual machine so that they are available when needed.

For help, see the https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Monitoring_CPU_utilization_before_an_ONTAP_upgrade[NetApp knowledgebase article about how to monitor ONTAP CPU utilization using the CLI^]
