---
sidebar: sidebar
permalink: concept-flash-cache.html
keywords: cloud volumes ontap, aws, ec2, flash cache, read-intensive, read, random, databases, email, file services, c5d.4xlarge, c5d.9xlarge, r5d.2xlarge, compression, performance, azure, nvme, standard, l8s, vm type, virtual machine, m5d.8xlarge, m5d.12xlarge, c5d.18xlarge
summary: Some Cloud Volumes ONTAP configurations in AWS and Azure include local NVMe storage, which Cloud Volumes ONTAP uses as Flash Cache for better performance.
---

= Flash Cache
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Some Cloud Volumes ONTAP configurations include local NVMe storage, which Cloud Volumes ONTAP uses as _Flash Cache_ for better performance.

== What's Flash Cache?

Flash Cache speeds access to data through real-time intelligent caching of recently read user data and NetApp metadata. It's effective for random read-intensive workloads, including databases, email, and file services.

== Supported configurations

Flash Cache is supported with specific Cloud Volumes ONTAP configurations. View supported configurations in the https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html[Cloud Volumes ONTAP Release Notes^]

== Limitations

* Compression must be disabled on all volumes to take advantage of the Flash Cache performance improvements.
+
Choose no storage efficiency when creating a volume from Cloud Manager, or create a volume and then http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html[disable data compression by using the CLI^].

* Cache rewarming after a reboot is not supported with Cloud Volumes ONTAP.
