---
sidebar: sidebar
permalink: concept-licensing-keystone.html
keywords: freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go
summary: Several licensing options are available for Cloud Volumes ONTAP. Each option enables you to choose a configuration that meets your needs.
---

= Keystone Flex Subscription overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A pay-as-you-grow subscription-based service that delivers a seamless hybrid cloud experience for those preferring OpEx consumption models to upfront CapEx or leasing.

Charging is based on the size of your committed capacity for one or more Cloud Volumes ONTAP HA pairs in your Keystone Flex Subscription.

The provisioned capacity for each volume is aggregated and compared to the committed capacity on your Keystone Flex Subscription periodically, and any overages are charged as burst on your Keystone Flex Subscription.

https://www.netapp.com/services/subscriptions/keystone/flex-subscription/[Learn more about Keystone Flex Subscriptions^].

=== Supported configurations

Keystone Flex Subscriptions are supported with HA pairs. This licensing option isn't supported with single node systems at this time.

=== Capacity limit

Each individual Cloud Volumes ONTAP system supports up to 2 PiB of capacity through disks and tiering to object storage.

=== How to get started

. If you don't have a subscription yet, https://www.netapp.com/forms/keystone-sales-contact/[contact NetApp^].
. mailto:ng-keystone-success@netapp.com[Contact NetApp] to authorize your Cloud Manager user account with one or more Keystone Flex Subscriptions.
. After NetApp authorizes your account, link:task-manage-keystone.html#link-a-subscription[link your subscriptions for use with Cloud Volumes ONTAP].
. Select the Keystone Flex Subscription charging method when you create a Cloud Volumes ONTAP system.
+
ifdef::aws[]
* link:task-deploying-otc-aws.html[Launching Cloud Volumes ONTAP in AWS]
endif::aws[]
ifdef::azure[]
* link:task-deploying-otc-azure.html[Launching Cloud Volumes ONTAP in Azure]
endif::azure[]
ifdef::gcp[]
* link:task-deploying-gcp.html[Launching Cloud Volumes ONTAP in Google Cloud]
endif::gcp[]
