---
sidebar: sidebar
permalink: concept-overview-cvo.html
keywords: what is cloud volumes ontap, cloud volumes ontap features, features, cloud volumes ontap overview, overview of cloud volumes ontap
summary: Cloud Volumes ONTAP enables you to optimize your cloud storage costs and performance while enhancing data protection, security, and compliance.
---

= Learn about Cloud Volumes ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP enables you to optimize your cloud storage costs and performance while enhancing data protection, security, and compliance.

Cloud Volumes ONTAP is a software-only storage appliance that runs ONTAP data management software in the cloud. It provides enterprise-grade storage with the following key features:

* Storage efficiencies
+
Leverage built-in data deduplication, data compression, thin provisioning, and cloning to minimize storage costs.

* High availability
+
Ensure enterprise reliability and continuous operations in case of failures in your cloud environment.

* Data protection
+
Cloud Volumes ONTAP leverages SnapMirror, NetApp's industry-leading replication technology, to replicate on-premises data to the cloud so it's easy to have secondary copies available for multiple use cases.
+
Cloud Volumes ONTAP also integrates with Cloud Backup service to deliver backup and restore capabilities for protection, and long-term archive of your cloud data.

* Data tiering
+
Switch between high and low-performance storage pools on-demand without taking applications offline.

* Application consistency
+
Ensure consistency of NetApp Snapshot copies using NetApp SnapCenter.

* Data security
+
Cloud Volumes ONTAP supports data encryption and provides protection against viruses and ransomware.

* Privacy compliance controls
+
Integration with Cloud Data Sense helps you understand data context and identify sensitive data.

NOTE: Licenses for ONTAP features are included with Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html[View supported Cloud Volumes ONTAP configurations^]

https://cloud.netapp.com/ontap-cloud[Learn more about Cloud Volumes ONTAP^]
