---
sidebar: sidebar
permalink: concept-client-protocols.html
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs
summary: Cloud Volumes ONTAP supports the iSCSI, NFS, SMB, NVMe-TCP, and S3 client protocols.
---

= Client protocols
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP supports the iSCSI, NFS, SMB, NVMe-TCP, and S3 client protocols.

== iSCSI

iSCSI is a block protocol that can run on standard Ethernet networks. Most client operating systems offer a software initiator that runs over a standard Ethernet port.

== NFS

NFS is the traditional file access protocol for UNIX and LINUX systems. Clients can access files in ONTAP volumes using the NFSv3, NFSv4, and NFSv4.1 protocols. You can control file access using UNIX-style permissions, NTFS-style permissions, or a mix of both.

Clients can access the same files using both NFS and SMB protocols.

== SMB

SMB is the traditional file access protocol for Windows systems. Clients can access files in ONTAP volumes using the SMB 2.0, SMB 2.1, SMB 3.0, and SMB 3.1.1 protocols. Just like with NFS, a mix of permission styles are supported.

ifdef::azure,aws[]

== S3

Cloud Volumes ONTAP supports S3 as an option for scale-out storage in the following cloud providers:

ifdef::aws[]
* AWS
endif::aws[]
ifdef::azure[]
* Azure
endif::azure[]

S3 protocol support enables you to configure S3 client access to objects contained in a bucket in an SVM.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html[Learn how to configure and manage S3 object storage services in ONTAP^].
endif::azure,aws[]

== NVMe-TCP

NVMe-TCP is supported for AWS, Azure, and GCP cloud providers if you are using Cloud Volumes ONTAP version 9.12.1 or newer. Configuration and workflows for NVMe-TCP are performed exclusively through ONTAP. 

For more information on configuring NVMe through ONTAP, see https://docs.netapp.com/us-en/ontap/task_nvme_provision_suse_linux.html[Provision NVMe storage for SUSE Linux^].