---
sidebar: sidebar
permalink: concept-performance.html
keywords: performance, technical report, TR, workload, cpu
summary: You can review performance results to help you decide which workloads are appropriate for Cloud Volumes ONTAP.
---

= Performance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can review performance results to help you decide which workloads are appropriate for Cloud Volumes ONTAP.

== Performance technical reports

* Cloud Volumes ONTAP for AWS
+
https://www.netapp.com/us/media/tr-4383.pdf[NetApp Technical Report 4383: Performance Characterization of Cloud Volumes ONTAP in Amazon Web Services with Application Workloads^].

* Cloud Volumes ONTAP for Microsoft Azure
+
https://www.netapp.com/us/media/tr-4671.pdf[NetApp Technical Report 4671: Performance Characterization of Cloud Volumes ONTAP in Azure with Application Workloads^].

* Cloud Volumes ONTAP for Google Cloud
+
https://www.netapp.com/us/media/tr-4816.pdf[NetApp Technical Report 4816: Performance Characterization of Cloud Volumes ONTAP for Google Cloud^].

== CPU performance

Cloud Volumes ONTAP nodes show as highly utilized (over 90%) from your cloud provider's monitoring tools. This is because ONTAP reserves all vCPUs presented to the virtual machine so that they are available when needed.

https://docs.netapp.com/us-en/cloud-manager-monitoring/concept-monitoring.html[Learn how to monitor Cloud Volumes ONTAP performance^], or check out this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Monitoring_CPU_utilization_before_an_ONTAP_upgrade[NetApp knowledgebase article about how to monitor ONTAP CPU utilization using the CLI^].
