---
sidebar: sidebar
permalink: concept-degraded-ha-pair.html
keywords: storage takeover, storage giveback, degraded, degraded status, degraded state, ha pair, ha takeover, takeover, giveback
summary: When a node in an HA pair isn't available, the other node serves data for its partner to provide continued data service. This is called storage takeover. Several actions are unavailable until in storage giveback is complete.
---

= Actions unavailable during takeover
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When a node in an HA pair isn't available, the other node serves data for its partner to provide continued data service. This is called _storage takeover_. Several actions are unavailable until in storage giveback is complete.

TIP: When a node in an HA pair is unavailable, the state of the working environment in BlueXP is _Degraded_.

The following actions are unavailable from BlueXP storage takeover:

* Support registration
* License changes
* Instance or VM type changes
* Write speed changes
* CIFS setup
* Changing the location of configuration backups
* Setting the cluster password
* Managing disks and aggregates (advanced allocation)

These actions are available again after storage giveback completes and the state of the working environment changes back to normal.
