settings:
  name: Cloud Volumes ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: All Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Volumes ONTAP docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new with Cloud Manager
          url: /whats-new.html
        - title: What's new with Cloud Volumes ONTAP
          url: /whats-new-ontap.html
        - title: Known limitations
          url: /reference-limitations.html
    - title: Get started
      entries:
        - title: Learn about Cloud Volumes ONTAP
          url: /concept-overview-cvo.html
        - title: Get started in Amazon Web Services
          entries:
            - title: Quick start
              url: /task-getting-started-aws.html
            - title: Plan your configuration
              url: /task-planning-your-config.html
            - title: Set up your networking
              entries:
                - title: Networking requirements
                  url: /reference-networking-aws.html
                - title: Set up an AWS transit gateway
                  url: /task-setting-up-transit-gateway.html
                - title: Security group rules for AWS
                  url: /reference-security-groups.html
            - title: Set up the AWS KMS
              url: /task-setting-up-kms.html
            - title: Launch a system in AWS
              url: /task-deploying-otc-aws.html
            - title: Get started in AWS C2S
              url: /task-getting-started-aws-c2s.html
        - title: Get started in Microsoft Azure
          entries:
            - title: Quick start
              url: /task-getting-started-azure.html
            - title: Plan your configuration
              url: /task-planning-your-config-azure.html
            - title: Set up your networking
              url: /reference-networking-azure.html
            - title: Set up encryption using your key
              url: /task-set-up-azure-encryption.html
            - title: Launch a system in Azure
              url: /task-deploying-otc-azure.html
        - title: Get started in Google Cloud
          entries:
            - title: Quick start
              url: /task-getting-started-gcp.html
            - title: Plan your configuration
              url: /task-planning-your-config-gcp.html
            - title: Set up your networking
              url: /reference-networking-gcp.html
            - title: Plan for VPC Service Controls
              url: /reference-vpc-service-controls-gcp.html
            - title: Create a service account
              url: /task-creating-gcp-service-account.html
            - title: Use customer-managed encryption keys
              url: /task-setting-up-gcp-encryption.html
            - title: Launch a system in GCP
              url: /task-deploying-gcp.html
    - title: Use Cloud Volumes ONTAP
      entries:
        - title: License management
          entries:
            - title: Manage capacity-based licenses
              url: /task-manage-capacity-licenses.html
            - title: Manage Keystone Flex Subscriptions
              url: /task-manage-keystone.html
            - title: Manage node-based licenses
              url: /task-manage-node-licenses.html
        - title: Volume and LUN administration
          entries:
            - title: Create volumes
              url: /task-create-volumes.html
            - title: Manage existing volumes
              url: /task-manage-volumes.html
            - title: Tier inactive data to object storage
              url: /task-tiering.html
            - title: Connect a LUN to a host
              url: /task-connect-lun.html
            - title: Accelerate data access with FlexCache
              url: /task-accelerate-data-access.html
            - title: Use ONTAP as persistent storage
              url: /task-connecting-kubernetes.html
        - title: Aggregate administration
          entries:
            - title: Create aggregates
              url: /task-create-aggregates.html
            - title: Manage existing aggregates
              url: /task-manage-aggregates.html
        - title: Storage VM administration
          entries:
            - title: Work with storage VMs in Cloud Manager
              url: /task-managing-svms.html
            - title: Create storage VMs in AWS
              url: /task-managing-svms-aws.html
            - title: Create storage VMs in Azure
              url: /task-managing-svms-azure.html
        - title: Security and data encryption
          entries:
            - title: Encrypt volumes with NetApp encryption
              url: /task-encrypting-volumes.html
            - title: Improve ransomware protection
              url: /task-protecting-ransomware.html
        - title: System administration
          entries:
            - title: Upgrade Cloud Volumes ONTAP
              url: /task-updating-ontap-cloud.html
            - title: Register pay-as-you-go systems
              url: /task-registering.html
            - title: Stop and start a system
              url: /task-managing-state.html
            - title: Synchronize system time
              url: /task-sync-time.html
            - title: Modify system write speed
              url: /task-modify-write-speed.html
            - title: Change the system password
              url: /task-change-password.html
            - title: Add, remove, or delete systems
              entries:
                - title: Add an existing system
                  url: /task-adding-systems.html
                - title: Remove a working environment
                  url: /task-removing.html
                - title: Delete a system
                  url: /task-deleting-working-env.html
            - title: Administration in AWS
              entries:
                - title: Change the EC2 instance type
                  url: /task-change-ec2-instance.html
                - title: Change route tables for HA pairs
                  url: /task-change-route-tables.html
                - title: Monitor AWS costs
                  url: /task-monitoring-costs.html
            - title: Administration in Azure
              entries:
                - title: Change the Azure VM type
                  url: /task-change-azure-vm.html
                - title: Override CIFS locks
                  url: /task-overriding-cifs-locks.html
                - title: Use an Azure Private Link
                  url: /task-enabling-private-link.html
            - title: Administration in Google Cloud
              entries:
                - title: Change the machine type
                  url: /task-change-gcp-machine.html
            - title: Administration from System Manager or CLI
              url: /task-connecting-to-otc.html
        - title: System health and events
          entries:
            - title: Verify AutoSupport setup
              url: /task-verify-autosupport.html
            - title: Configure EMS
              url: /task-configure-ems.html
    - title: Concepts
      entries:
        - title: Storage
          entries:
            - title: Disks and aggregates
              url: /concept-storage.html
            - title: Data tiering
              url: /concept-data-tiering.html
            - title: Storage management
              url: /concept-storage-management.html
            - title: Write speed
              url: /concept-write-speed.html
            - title: Flash Cache
              url: /concept-flash-cache.html
            - title: WORM storage
              url: /concept-worm.html
        - title: High-availability pairs
          entries:
            - title: HA pairs in AWS
              url: /concept-ha.html
            - title: HA pairs in Azure
              url: /concept-ha-azure.html
            - title: HA pairs in GCP
              url: /concept-ha-google-cloud.html
            - title: Actions during storage takeover
              url: /concept-degraded-ha-pair.html
        - title: Licensing
          url: /concept-licensing.html
        - title: Management of node-based BYOL
          url: /concept-license-management.html
        - title: Security
          url: /concept-security.html
        - title: Performance
          url: /concept-performance.html
        - title: AutoSupport and Active IQ Digital Advisor
          url: /concept-active-iq.html
        - title: Default configuration
          url: /reference-default-configs.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about Cloud Volumes ONTAP
          url: concept-overview-cvo.html
        - title: Quick start for AWS
          url: task-getting-started-aws.html
        - title: Quick start for Azure
          url: task-getting-started-azure.html
        - title: Quick start for Google Cloud
          url: task-getting-started-gcp.html
    - title: Licensing
      links:
        - title: Licensing overview
          url: concept-licensing.html
        - title: Manage capacity-based licenses
          url: task-manage-capacity-licenses.html
        - title: Manage Keystone Flex Subscriptions
          url: task-manage-keystone.html
    - title: Storage management
      links:
        - title: Create volumes
          url: task-create-volumes.html
        - title: Tier inactive data to object storage
          url: task-tiering.html
        - title: Accelerate data access with FlexCache
          url: task-accelerate-data-access.html
    - title: System administration
      links:
        - title: Upgrade Cloud Volumes ONTAP
          url: task-updating-ontap-cloud.html
        - title: Stop and start Cloud Volumes ONTAP
          url: task-managing-state.html
    - title: Security
      links:
        - title: Encrypt volumes with NetApp encryption
          url: task-encrypting-volumes.html
        - title: Improve ransomware protection
          url: task-protecting-ransomware.html
    - title: API
      links:
        - title: Overview of the Cloud Volumes ONTAP API
          url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/overview.html
        - title: Prepare to use the API
          url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/prepare.html
        - title: API reference
          url: https://docs.netapp.com/us-en/cloud-manager-automation/cm/api_ref_resources.html
    - title: Troubleshooting
      links:
        - title: NetApp Knowledge Base
          url: https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)
    - title: Reference
      links:
        - title: Supported configurations
          url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html
        - title: Supported cloud regions
          url: https://cloud.netapp.com/cloud-volumes-global-regions
        - title: Calculators
          url: https://cloud.netapp.com/calculator-hub
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
