settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Volumes ONTAP docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Get started in AWS
          entries:
            - title: Quick start
              url: /task-getting-started-aws.html
            - title: Plan your configuration
              url: /task-planning-your-config.html
            - title: Set up your networking
              entries:
                - title: Networking requirements
                  url: /reference-networking-aws.html
                - title: Set up an AWS transit gateway
                  url: /task-setting-up-transit-gateway.html
                - title: Security group rules for AWS
                  url: /reference-security-groups.html
            - title: Set up the AWS KMS
              url: /task-setting-up-kms.html
            - title: Launch a system in AWS
              url: /task-deploying-otc-aws.html
            - title: Get started in AWS C2S
              url: /task-getting-started-aws-c2s.html
        - title: Get started in Azure
          entries:
            - title: Quick start
              url: /task-getting-started-azure.html
            - title: Plan your configuration
              url: /task-planning-your-config-azure.html
            - title: Set up your networking
              url: /reference-networking-azure.html
            - title: Set up encryption using your key
              url: /task-set-up-azure-encryption.html
            - title: Launch a system in Azure
              url: /task-deploying-otc-azure.html
        - title: Get started in GCP
          entries:
            - title: Quick start
              url: /task-getting-started-gcp.html
            - title: Plan your configuration
              url: /task-planning-your-config-gcp.html
            - title: Set up your networking
              url: /reference-networking-gcp.html
            - title: Plan for VPC Service Controls
              url: /reference-vpc-service-controls-gcp.html
            - title: Create a service account
              url: /task-creating-gcp-service-account.html
            - title: Use customer-managed encryption keys
              url: /task-setting-up-gcp-encryption.html
            - title: Launch a system in GCP
              url: /task-deploying-gcp.html
    - title: Manage Cloud Volumes ONTAP
      entries:
        - title: Provision and manage storage
          entries:
            - title: Create volumes, aggregates, and LUNs
              url: /task-provisioning-storage.html
            - title: Manage volumes and aggregates
              url: /task-managing-storage.html
            - title: Tier inactive data to object storage
              url: /task-tiering.html
            - title: Use ONTAP as persistent storage
              url: /task-connecting-kubernetes.html
            - title: Encrypt volumes with NetApp encryption
              url: /task-encrypting-volumes.html
        - title: Manage storage VMs
          entries:
            - title: Work with storage VMs in Cloud Manager
              url: /task-managing-svms.html
            - title: Create storage VMs in AWS
              url: /task-managing-svms-aws.html
            - title: Create storage VMs in Azure
              url: /task-managing-svms-azure.html
        - title: Optimize with Active IQ Digital Advisor
          url: /concept-cvo-aiq-digital-advisor.html
        - title: Improve ransomware protection
          url: /task-protecting-ransomware.html
        - title: Administer
          entries:
            - title: Manage licenses
              url: /task-managing-licenses.html
            - title: Register pay-as-you-go systems
              url: /task-registering.html
            - title: Set up Cloud Volumes ONTAP
              url: /task-setting-up-ontap-cloud.html
            - title: Update software
              url: /task-updating-ontap-cloud.html
            - title: Modify system configurations
              url: /task-modifying-ontap-cloud.html
            - title: Stop and start systems
              url: /task-managing-state.html
            - title: Monitor AWS costs
              url: /task-monitoring-costs.html
            - title: Connect to Cloud Volumes ONTAP
              url: /task-connecting-to-otc.html
            - title: Add existing systems
              url: /task-adding-ontap-cloud.html
            - title: Override CIFS locks in Azure
              url: /task-overriding-cifs-locks.html
            - title: Use an Azure Private Link
              url: /task-enabling-private-link.html
            - title: Delete systems
              url: /task-deleting-working-env.html
    - title: Concepts
      entries:
        - title: Overview
          url: /concept-overview-cvo.html
        - title: Storage
          entries:
            - title: Disks and aggregates
              url: /concept-storage.html
            - title: Data tiering
              url: /concept-data-tiering.html
            - title: Storage management
              url: /concept-storage-management.html
            - title: Write speed
              url: /concept-write-speed.html
            - title: Flash Cache
              url: /concept-flash-cache.html
            - title: WORM storage
              url: /concept-worm.html
            - title: High-availability pairs
              entries:
                - title: HA pairs in AWS
                  url: /concept-ha.html
                - title: HA pairs in Azure
                  url: /concept-ha-azure.html
                - title: HA pairs in GCP
                  url: /concept-ha-google-cloud.html
                - title: Actions during storage takeover
                  url: /concept-degraded-ha-pair.html
            - title: Licensing
              url: /concept-licensing.html
            - title: Management of node-based BYOL
              url: /concept-license-management.html
            - title: Evaluating
              url: /concept-evaluating.html
            - title: Security
              url: /concept-security.html
            - title: Performance
              url: /concept-performance.html
            - title: Supported configurations
              url: https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html
            - title: Supported regions
              url: https://cloud.netapp.com/cloud-volumes-global-regions
            - title: AutoSupport and Active IQ Digital Advisor
              url: /concept-active-iq.html
            - title: Default configuration
              url: /reference-default-configs.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
    - title: <tile name>
      links:
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
        - title: <title>
          url: <page.html>
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
