---
sidebar: sidebar
permalink: reference-default-configs.html
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features
summary: Understanding how Cloud Volumes ONTAP is configured by default can help you set up and administer your systems, especially if you are familiar with ONTAP because the default setup for Cloud Volumes ONTAP is different than ONTAP.
---

= Default configuration for Cloud Volumes ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Understanding how Cloud Volumes ONTAP is configured by default can help you set up and administer your systems, especially if you are familiar with ONTAP because the default setup for Cloud Volumes ONTAP is different than ONTAP.

== Defaults

* Cloud Volumes ONTAP is available as a single-node system and as an HA pair in AWS, Azure, and GCP.

* Cloud Manager creates one data-serving storage VM when it deploys Cloud Volumes ONTAP. Some configurations support additional storage VMs. link:task-managing-svms.html[Learn more about managing storage VMs].
+
Starting with the Cloud Manager 3.9.5 release, logical space reporting is enabled on the initial storage VM. When space is reported logically, ONTAP reports the volume space such that all the physical space saved by the storage efficiency features are also reported as used.

* Cloud Manager automatically installs the following ONTAP feature licenses on Cloud Volumes ONTAP:
** CIFS
** FlexCache
** FlexClone
** iSCSI
** NetApp Volume Encryption (only for BYOL or registered PAYGO systems)
** NFS
** SnapMirror
** SnapRestore
** SnapVault

* Several network interfaces are created by default:
** A cluster management LIF
** An intercluster LIF
** An SVM management LIF on HA systems in Azure and in GCP, on single node systems in AWS, and optionally on HA systems in multiple AWS Availability Zones
** A node management LIF (in GCP, this LIF is combined with the intercluster LIF)
** An iSCSI data LIF
** A CIFS and NFS data LIF
+
NOTE: LIF failover is disabled by default for Cloud Volumes ONTAP due to EC2 requirements. Migrating a LIF to a different port breaks the external mapping between IP addresses and network interfaces on the instance, making the LIF inaccessible.

* Cloud Volumes ONTAP sends configuration backups to the Connector using HTTPS.
+
The backups are accessible from https://ipaddress/occm/offboxconfig/ where _ipaddress_ is the IP address of the Connector host.

* Cloud Manager sets a few volume attributes differently than other management tools (System Manager or the CLI, for example).
+
The following table lists the volume attributes that Cloud Manager sets differently from the defaults:
+
[cols=2*,options="header",cols="15,85"]
|===

| Attribute
| Value set by Cloud Manager

| Autosize mode |	grow
| Maximum autosize
a| 1,000 percent

NOTE: The Account Admin can modify this value from the Settings page.

| Security style |	NTFS for CIFS volumes
UNIX for NFS volumes
| Space guarantee style |	none
| UNIX permissions (NFS only) |	777

|===
+
See the _volume create_ man page for information about these attributes.

== Internal disks for system data

In addition to the storage for user data, Cloud Manager also purchases cloud storage for system data.

=== AWS

* Three disks per node for boot, root, and core data:
** 45 GiB io1 disk for boot data
** 140 GiB gp3 disk for root data
** 540 GiB gp2 disk for core data

* One EBS snapshot for each boot disk and root disk

* For HA pairs, one EBS volume for the Mediator instance, which is approximately 8 GiB

TIP: In AWS, NVRAM is on the boot disk.

=== Azure (single node)

* Three Premium SSD disks:
** One 10 GiB disk for boot data
** One 140 GiB disk for root data
** One 512 GiB disk for NVRAM
+
If the virtual machine that you chose for Cloud Volumes ONTAP supports Ultra SSDs, then the system uses a 32 GiB Ultra SSD for NVRAM, rather than a Premium SSD.

* One 1024 GiB Standard HDD disk for saving cores

* One Azure snapshot for each boot disk and root disk

=== Azure (HA pair)

*	Two 10 GiB Premium SSD disks for the boot volume (one per node)
* Two 140 GiB Premium Storage page blobs for the root volume (one per node)
* Two 1024 GiB Standard HDD disks for saving cores (one per node)
* Two 512 GiB Premium SSD disks for NVRAM (one per node)
* One Azure snapshot for each boot disk and root disk

=== Google Cloud (single node)

* One 10 GiB SSD persistent disk for boot data
* One 64 GiB SSD persistent disk for root data
* One 500 GiB SSD persistent disk for NVRAM
* One 315 GiB Standard persistent disk for saving cores
* Snapshots for boot and root data

=== Google Cloud (HA pair)

* Two 10 GiB SSD persistent disks for boot data
* Four 64 GiB SSD persistent disk for root data
* Two 500 GiB SSD persistent disk for NVRAM
* Two 315 GiB Standard persistent disk for saving cores
* One 10 GiB Standard persistent disk for mediator data
* Snapshots for boot and root data

=== Where the disks reside

Cloud Manager lays out the storage as follows:

* Boot data resides on a disk attached to the instance or virtual machine.
+
This disk, which contains the boot image, is not available to Cloud Volumes ONTAP.

* Root data, which contains the system configuration and logs, resides in aggr0.

* The storage virtual machine (SVM) root volume resides in aggr1.

* Data volumes also reside in aggr1.

=== Encryption

Boot and root disks are always encrypted in Azure and Google Cloud Platform because encryption is enabled by default in those cloud providers.

When you enable data encryption in AWS using the Key Management Service (KMS), the boot and root disks for Cloud Volumes ONTAP are encrypted, as well. This includes the boot disk for the mediator instance in an HA pair. The disks are encrypted using the CMK that you select when you create the working environment.
