---
sidebar: sidebar
permalink: task-file-verification-linux.html
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP,
Cloud Volumes, CLI, Linux 
summary: Verify an exported VHD file signature through the Cloud Volumes ONTAP 
Image Digest File tool on Linux
---

= File Signature Verification on Linux 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can verify an exported VHD file signature through the Cloud Volumes ONTAP Image Digest File tool. The digest file tool removes the leading 1MB from the VHD file and then verifies the remaining portion of the exported VHD file.
 
.Steps

. Download the digest file(.sig), public key certificate file(.pem) and chain certificate file(.pem) from NSS website.  

. Place the download files in a local directory. 
+
If tar.gz is the downloaded format, use "tar -xzf".

. Verify the chain of trust.
+
----
% openssl verify -CAfile Certificate-Chain-AZURE_CVO_20230124-134845.pem Certificate-AZURE_CVO_20230124-134845.pem
Certificate-AZURE_CVO_20230124-134845.pem: OK
----

. Remove the leading 1MB (1048576 Bytes) of VHD file. If 'tail' is used, the option '-c +K' outputs bytes starting with the Kth bytes of the specified file. Hence, 1048577 is passed to 'tail -c'.
+
----
% tail -c +1048577 ./9.130.20230209.vhd > ./sign.tmp
----

. Use openssl to extract public key from certificate and verify the striped file(sign.tmp) with the signature file and public key. 
+
If the input file passes the verification, the command will display 
"Verification OK". Otherwise, "Verification Failure" will display.
+
----
% openssl x509 -pubkey -noout -in ./Code-Sign-Cert.pem > ./Code-Sign-Cert-Public-key.pub
 
% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verification OK
 
% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----

. Clean up the workspace.
+ 
----
% rm ./9.130.20230209.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----
