---
sidebar: sidebar
permalink: task-file-verification-mac.html
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, Mac OS 
summary: Verify an exported VHD file signature through the Cloud Volumes ONTAP Image Digest File tool on Mac OS
---

= File signature verification on Mac OS 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can verify an exported VHD file signature for Mac OS by following the steps below.

.Steps

. Download the Azure Image Digest file from the https://mysupport.netapp.com/site/[NetApp Support Site^] and extract the digest file(.sig), public key certificate file(.pem) and chain certificate file(.pem).
+
Refer to the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html[Download the Azure Image Digest File^] for more information. 

. Verify the chain of trust.
+
----
% openssl verify -CAfile Certificate-Chain-AZURE_CVO_20230124-134845.pem Certificate-AZURE_CVO_20230124-134845.pem
Certificate-AZURE_CVO_20230124-134845.pem: OK
----

. Remove the leading 1MB(1048576 Bytes) and ending 512 Bytes of VHD file. 
+
If 'tail' is used, the option '-c +K' outputs bytes starting with the Kth bytes 
of the specified file. Hence, 1048577 is passed to 'tail -c'. It takes around 13m 
for the tail command to complete on Mac OS.
+
----
% tail -c +1048577 ./devN_221119_0200.vhd > ./sign.tmp
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----

. Use openssl to extract public key from certificate and verify the striped 
file(sign.tmp) with the signature file and public key. 
+
If the input file passes the verification, the command will display "Verification OK". 
Otherwise, "Verification Failure" will display.
+
----
% openssl x509 -pubkey -noout -in ./Certificate-AZURE_CVO_20230124-134845.pem > ./Code-Sign-Cert-Public-key.pub
 
% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verified OK
 
% openssl dgst -verify public_key.pem -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----

. Clean up the workspace.
+ 
----
% rm ./9.110.20220302.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----


