---
sidebar: sidebar
permalink: task-saz-feature.html
keywords: Microsoft Azure feature, HA in SAZ, single availability zone, Azure feature, Virtual Machine Scale Sets in Flexible mode
---
summary: Enable this Microsoft Azure feature to deploy HA in SAZ.
---

= Enable HA deployment in single availability zones
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
For enabling Azure's high availability mode in a single availability zone, you should activate the Microsoft `Microsoft.Compute/VMOrchestratorZonalMultiFD` feature for your subscriptions.

Cloud Volumes ONTAP 9.15.1 and later leverage Azure Virtual Machine Scale Sets in Flexible orchestration mode for the deployment of VM instances in single availability zones. This feature facilitates the creation of separate fault domains within the same availability zone to ensure availability and scalability.

Perform these steps as a user with "Owner" privileges from Azure CLI:

.Steps

. Register for the `Microsoft.Compute/VMOrchestratorZonalMultiFD` feature by running this command:
+
====
az feature register --name VMOrchestratorZonalMultiFD --namespace Microsoft.Compute
====
+
. Verify the registration status and output sample:
+
====
PS /home/<instance> az feature show -n VMOrchestratorZonalMultiFD --namespace Microsoft.Compute
{
  "id": "/subscriptions/<ID>/providers/Microsoft.Features/providers/Microsoft.Compute/features/VMOrchestratorZonalMultiFD",
  "name": "Microsoft.Compute/VMOrchestratorZonalMultiFD",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
====

