---
sidebar: sidebar
permalink: task-file-verification-mac.html
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, Mac OS 
summary: Verify an exported VHD file signature through the Cloud Volumes ONTAP image digest File tool on Mac OS
---

= Verify Azure marketplace image signature for Cloud Volumes ONTAP on MAC OS 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can verify an exported VHD file signature on Mac OS by following these steps.

.Steps

. Download the Azure image file from the https://mysupport.netapp.com/site/[NetApp Support Site^] and extract the digest (.sig) file, public key certificate (.pem) file, and chain certificate (.pem) file.
+
Refer to https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html[Download the Azure image digest file^] for more information.

. Verify the chain of trust.
+
[source,cli]
----
% openssl verify -CAfile Certificate-Chain-9.15.0P1_azure.pem Certificate-9.15.0P1_azure.pem
Certificate-9.15.0P1_azure.pem: OK
----
+
. Remove the leading 1MB (1,048,576 bytes) and trailing 512 bytes from the VHD file.
When using `tail`, the `-c +K` option generates bytes from the Kth byte of the file. Therefore, it passes 1048577 to `tail -c`. Note that on Mac OS, the tail command may take a little while to complete.
+
[source,cli]
----
% tail -c +1048577 ./9150.01000024.05090105.vhd > ./sign.tmp.tail
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----
+
. Use OpenSSL to extract the public key from the certificate and verify the stripped file (sign.tmp) with the signature file and public key. The command prompt displays messages indicating success or failure based on the verification.
+
[source,cli]
----
% openssl x509 -pubkey -noout -in ./Certificate-9.15.0P1_azure.pem > ./Code-Sign-Cert-Public-key.pub

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verified OK

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----
+
. Clean up the workspace.
+
[source,cli]
----
% rm ./9150.01000024.05090105.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----


