---
sidebar: sidebar
permalink: task-managing-svms-gcp.html
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver
summary: A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an SVM or a vserver. Cloud Volumes ONTAP is configured with one storage VM by default, but some configurations support additional storage VMs.
---

= Create data-serving storage VMs for Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an _SVM_ or a _vserver_. Cloud Volumes ONTAP is configured with one storage VM by default, but some configurations support additional storage VMs.

To create and manage additional data-serving storage VMs in Google Cloud, you should use the BlueXP APIs. This is because the APIs automate the process of creating the storage VMs and configuring the required network interfaces. When creating the storage VMs, BlueXP configures the required LIF services, as well as an iSCSI LIF that's required for outbound SMB/CIFS communications from the storage VM.

== Supported number of storage VMs

Multiple storage VMs are supported with specific Cloud Volumes ONTAP configurations in Google Cloud starting with the 9.11.1 release. Go to the https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html[Cloud Volumes ONTAP Release Notes^] to verify the supported number of storage VMs for your version of Cloud Volumes ONTAP.

All other Cloud Volumes ONTAP configurations support one data-serving storage VM and one destination storage VM used for disaster recovery. You can activate the destination storage VM for data access if there's an outage on the source storage VM.

.Before you begin

== Create a storage VM

Based on your configuration and license type, you can create multiple storage VMs on a single node system or in a high-availability (HA) configuration by using the BlueXP APIs.

.About this task

When you create storage VMs using the APIs, along with configuring the required network interfaces, BlueXP also modifies the `default-data-files` policies on the data storage VMs by removing the following services from the NAS data LIF and adding them to the iSCSI data LIF that's used for outbound management connections:

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.Before you begin

The Connector requires specific permissions to create and manage storage VMs for Cloud Volumes ONTAP HA pairs. The required permissions are included in https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html[the policies provided by NetApp^].

=== Single node system


=== HA pair

.Steps

. Use the following API call to create a storage VM:
+
`POST /gcp/ha/working-environments/{workingEnvironmentId}/svm/`
+
The request body should include the following:
+
[source,json]
{ "svmName": "myNewSvm1" }

== Manage storage VMs 

The BlueXP API also supports renaming and deleting storage VMs on HA pairs.

=== Rename a storage VM

If needed, you can change the name of a storage VM at any time.

.Steps

. Use the following API call to rename a storage VM:
+
`PUT /gcp/ha/working-environments/{workingEnvironmentId}/svm`
+
The request body should include the following:
+
[source,json]
{
"svmNewName": "newSvmName",
"svmName": "oldSvmName"
}

=== Delete a storage VM

If you no longer need a storage VM, you can delete it from Cloud Volumes ONTAP.

.Steps

. Use the following API call to delete a storage VM:
+
`DELETE /gcp/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`
