---
sidebar: sidebar
permalink: task-accelerate-data-access.html
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume
summary: A FlexCache volume is a storage volume that caches NFS read data from an origin or source volume. Subsequent reads to the cached data result in faster access to that data.
---

= Accelerate data access with FlexCache volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A FlexCache volume is a storage volume that caches SMB and NFS read data from an origin (or source) volume. Subsequent reads to the cached data result in faster access to that data.

You can use FlexCache volumes to speed up access to data or to offload traffic from heavily accessed volumes. FlexCache volumes help improve performance, especially when clients need to access the same data repeatedly, because the data can be served directly without having to access the origin volume. FlexCache volumes work well for system workloads that are read-intensive.

BlueXP provides management of FlexCache volumes with the link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html[BlueXP volume caching^] service. 

You can also use the ONTAP CLI or ONTAP System Manager to create and manage FlexCache volumes:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html[FlexCache Volumes for Faster Data Access Power Guide^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html[Creating FlexCache volumes in System Manager^]

BlueXP generates a FlexCache license for all new Cloud Volumes ONTAP systems. The license includes a 500 GiB usage limit.

video::PBNPVRUeT1o[youtube, width=848, height=480]

== Work with FlexCache when the origin is encrypted

When configuring FlexCache on a Cloud Volumes ONTAP system where the origin volume is encrypted, additional steps are required, to ensure that the FlexCache volume can properly access and cache the encrypted data. 

.What you'll need
. *Encryption setup*: Ensure that the source volume is fully encrypted and operational. For Cloud Volumes ONTAP systems, this involves integrating with cloud-specific key management services.
ifdef::aws[]
For AWS, this typically means using AWS Key Management Service (KMS). For information, refer to link:task-aws-key-management.html[Manage keys with AWS Key Management Service].
endif::aws[]
ifdef::azure[]
For Azure, you need to set up Azure Key Vault for NetApp Volume Encryption (NVE). For information, refer to link:task-azure-key-vault.html[Manage keys with Azure Key Vault].
endif::azure[]
ifdef::gcp[]
For Google Cloud, it is Google Cloud Key Management Service. For information, refer to link:task-google-key-manager.html[Manage keys with Google's Cloud Key Management Service].
endif::gcp[]
. *Key management services*: Before creating a FlexCache volume, verify that the key management services are configured correctly on the Cloud Volumes ONTAP system. This configuration is essential for the FlexCache volume to decrypt the data from the origin volume.
. *Licensing*: Confirm that a valid FlexCache license is available and activated on the Cloud Volumes ONTAP system. BlueXP generates a FlexCache license for all new Cloud Volumes ONTAP systems with a 500 GiB usage limit.
. *ONTAP version*: Ensure that the ONTAP version of your Cloud Volumes ONTAP system supports FlexCache with encrypted volumes. Refer to the latest https://docs.netapp.com/us-en/ontap/release-notes/index.html[ONTAP release notes^] or compatibility matrix for more information.
. *Network Configuration*: Ensure that the network configuration allows for seamless communication between the origin volume and the FlexCache volume. This includes proper routing and DNS resolution in a cloud environment.

.Steps
Create a FlexCache volume on your Cloud Volumes ONTAP system with an encrypted source volume. For detailed steps and additional considerations, refer to the following sections:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html[FlexCache Volumes for Faster Data Access Power Guide^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html[Creating FlexCache volumes in System Manager^]

//BLUEXPDOC-119: GH CVO issue# 311
