---
sidebar: sidebar
permalink: task-deploy-aws-shared-vpc.html
keywords: shared vpc, aws shared vpc, vpc sharing, shared subnet, deploy shared vpc, assume role
summary: Cloud Volumes ONTAP HA pairs are supported in AWS with VPC sharing. VPC sharing enables your organization to share subnets with other AWS accounts. To use this configuration, you must set up your AWS environment and then deploy the HA pair using the API.
---

= Deploy an HA pair in a shared subnet
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP HA pairs are supported in AWS with VPC sharing. VPC sharing enables your organization to share subnets with other AWS accounts. To use this configuration, you must set up your AWS environment and then deploy the HA pair using the API.

With https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-sharing-a-new-approach-to-multiple-accounts-and-vpc-management/[VPC sharing^], a Cloud Volumes ONTAP HA configuration is spread across two accounts:

* The VPC owner account, which owns the networking (the VPC, subnets, and route tables)
* The participant account, where the EC2 instances are deployed in shared subnets (this includes the two HA nodes and the mediator)

In the case of a Cloud Volumes ONTAP HA configuration that is deployed across multiple Availability Zones, the HA mediator needs specific permissions to write to the route tables in the VPC owner account. You need to provide those permissions by setting up an IAM role that the mediator can assume.

.Steps

. Create an IAM role.

.. Go to the IAM console in the participant account where you want to deploy the EC2 instances for Cloud Volumes ONTAP.

.. Under Access Management, click *Roles > Create Role* and follow the steps to create the role.
+
Be sure to do the following:

* Under *Trusted entity type*, select *AWS account*.
* Select *Another AWS account* and enter the ID of the account where the Connector instance resides.
* Create a policy using the Cloud Manager IAM policy, which is available from the https://mysupport.netapp.com/site/info/cloud-manager-policies[Cloud Manager Policies page^].

.. Copy the Role ARN of the IAM role so that you can paste it in the API request when you deploy the HA pair.

. Share the subnets in the VPC owner account with the participant account.
+
This step is required to deploy the HA pair in the shared subnets.
+
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html#vpc-sharing-share-subnet[AWS documentation: Share a subnet^]

. In the VPC owner account, create a security group for Cloud Volumes ONTAP.
+
link:reference-security-groups.html[Refer to the rules for Cloud Volumes ONTAP]. Note that you don't need to create a security group for the HA mediator. Cloud Manager does that for you.

. Use the API to create a new Cloud Volumes ONTAP working environment and pass the "assumeRoleArn" field in the "haParams" object.

[source,json]
"haParams": {
     “assumeRoleArn”: “arn:aws:iam::642991768967:role/mediator_role_assume_fromdev”
}
