---
sidebar: sidebar
permalink: task-encrypting-volumes.html
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption
summary: Cloud Volumes ONTAP supports both NetApp Volume Encryption (NVE) and NetApp Aggregate Encryption (NAE) with an external key manager. NVE and NAE are enabled by default if you set up an external key manager.
---
= Encrypting volumes with NetApp encryption solutions
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP supports NetApp Volume Encryption (NVE) and NetApp Aggregate Encryption (NAE). NVE and NAE are software-based solutions that enable FIPS 140-2–compliant data-at-rest encryption of volumes. link:concept-security.html[Learn more about these encryption solutions].

Both NVE and NAE are supported with an external key manager.

ifdef::aws,azure,gcp[]
If you use NVE, you have the option to use your cloud provider's key vault to protect ONTAP encryption keys:

ifdef::aws[]
* AWS Key Management Service (beginning in 9.12.0)
endif::aws[]
ifdef::azure[]
* Azure Key Vault (AKV)
endif::azure[]
ifdef::gcp[]
* Google Cloud Key Management Service
endif::gcp[]
endif::azure,gcp[]

New aggregates will have NAE enabled by default after you set up an external key manager. New volumes that aren't part of an NAE aggregate will have NVE enabled by default (for example, if you have existing aggregates that were created before setting up an external key manager).

Cloud Volumes ONTAP doesn't support onboard key management.

.What you'll need

Your Cloud Volumes ONTAP system should be registered with NetApp support. A NetApp Volume Encryption license is automatically installed on each Cloud Volumes ONTAP system that is registered with NetApp Support.

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html[Adding NetApp Support Site accounts to BlueXP^]
* link:task-registering.html[Registering pay-as-you-go systems]

NOTE: BlueXP doesn't install the NVE license on systems that reside in the China region.

.Steps

. Review the list of supported key managers in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
+
TIP: Search for the *Key Managers* solution.

. link:task-connecting-to-otc.html[Connect to the Cloud Volumes ONTAP CLI^].

. Configure external key management.
+
ifdef::aws[]
* AWS: link:task-aws-key-management.html[AWS Key Management Service]
endif::aws[]
ifdef::azure[]
* Azure: link:task-azure-key-vault.html[Azure Key Vault (AKV)]
endif::azure[]
ifdef::gcp[]
* Google Cloud: link:task-google-key-manager.html[Google Cloud Key Management Service]
endif::gcp[]

// BLUEXPDOC-10