---
sidebar: sidebar
permalink: task-accelerate-data-access.html
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume
summary: A FlexCache volume is a storage volume that caches NFS read data from an origin or source volume. Subsequent reads to the cached data result in faster access to that data.
---

= Accelerate data access with FlexCache volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A FlexCache volume is a storage volume that caches SMB and NFS read data from an origin (or source) volume. Subsequent reads to the cached data result in faster access to that data.

You can use FlexCache volumes to speed up access to data or to offload traffic from heavily accessed volumes. FlexCache volumes help improve performance, especially when clients need to access the same data repeatedly, because the data can be served directly without having to access the origin volume. FlexCache volumes work well for system workloads that are read-intensive.

BlueXP provides management of FlexCache volumes with the link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html[BlueXP volume caching^] service. 

You can also use the ONTAP CLI or ONTAP System Manager to create and manage FlexCache volumes:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html[FlexCache Volumes for Faster Data Access Power Guide^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html[Creating FlexCache volumes in System Manager^]

BlueXP generates a FlexCache license for all new Cloud Volumes ONTAP systems. The license includes a 500 GiB usage limit.

video::PBNPVRUeT1o[youtube, width=848, height=480]
