---
sidebar: sidebar
permalink: task-deploy-cvo-azure-mktplc.html
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace
summary: 
---

= Deploy Cloud Volumes ONTAP from the Azure marketplace
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with Cloud Volumes ONTAP 9.16.1, you can use Azure marketplace direct deployment to quickly and easily deploy Cloud Volumes ONTAP. From the Azure marketplace, you can quickly deploy Cloud Volumes ONTAP in a few clicks and explore its core features and capabilities in your environment. 

For more information about this offering, refer to link:concept-azure-mktplace-direct.html[Learn about Cloud Volumes ONTAP offerings on BlueXP and the marketplace].

.About this task
The Cloud Volumes ONTAP system deployed by using Azure marketplace direct deployment has these properties: 

* The latest Cloud Volumes ONTAP version (9.16.1 or later).
* A free license for Cloud Volumes ONTAP that is limited to 500 GiB of provisioned capacity. This license includes no NetApp support and has no expiry date.
* Two nodes configured in a high availability (HA) mode in a single availability zone (AZ), provisioned with default serial numbers. The storage virtual machines (storage VMs) are deployed in a link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks[flexible orchestration mode].
* An aggregate for the instance created by default.
* A Premium SSD v2 Managed Disk of 500 GiB provisioned capacity, and a root and a data disk.
* One data storage VM deployed, with  NFS, CIFS, iSCSI, and NVMe/TCP data-services. You cannot add any additional data storage VMs.
* Licenses installed for NFS, CIFS (SMB), iSCSI, Autonomous Ransomware Protection (ARP), SnapLock, and SnapMirror.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html[ONTAP temperature-sensitive storage efficiency (TSSE)^], volume encryption, and external key-management enabled by default.
* These features are not supported:
** FabricPool tiering
** Changing the storage VM type
** Fast write mode


.Before you begin
* Ensure that you have a valid Azure marketplace subscription.
* Ensure you meet the networking requirements for an link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks[HA deployment in a single AZ] in Azure. Refer to link:reference-networking-azure.html[Set up Azure networking for Cloud Volumes ONTAP].
* You need to be assigned one of these Azure roles to deploy Cloud Volumes ONTAP:
** The `contributor` role with the default permissions. For more information, refer to the https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles[Azure documentation: Azure built-in roles^].
** A custom RBAC role with the following permissions. For more information, refer to the https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles[Azure documentation: Azure custom roles^].
+ 
====
"permissions": [
            {
                "actions": [
                  "Microsoft.AAD/register/action",
                    "Microsoft.Resources/subscriptions/resourceGroups/write",
                    "Microsoft.Network/loadBalancers/write",
                    "Microsoft.ClassicCompute/virtualMachines/write",
                    "Microsoft.Compute/capacityReservationGroups/deploy/action",
                    "Microsoft.ClassicCompute/virtualMachines/networkInterfaces/associatedNetworkSecurityGroups/write",
                    "Microsoft.Network/networkInterfaces/write",
                    "Microsoft.Compute/virtualMachines/write",
                    "Microsoft.Compute/virtualMachines/extensions/write",
                    "Microsoft.Resources/deployments/validate/action",
                    "Microsoft.Resources/subscriptions/resourceGroups/read",
                    "Microsoft.Network/virtualNetworks/write",
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Network/networkSecurityGroups/write",
                    "Microsoft.Network/networkSecurityGroups/read",
                    "Microsoft.Compute/disks/write",
                    "Microsoft.Compute/virtualMachineScaleSets/write",
                    "Microsoft.Resources/deployments/write",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Network/virtualNetworks/subnets/write"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]


====
+
[NOTE]
If you have registered the resource provider "Microsoft.storage" to your subscription, then you don't need the `Microsoft.AAD/register/action` permission. For more information, refer to the https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage[Azure documentation: Azure permissions for Storage^].

.Steps
. From the Azure marketplace site, search for NetApp products.
. Select *NetApp Cloud Volumes ONTAP direct*.
. Click *Create* to launch the deployment wizard.
. Select a plan. The *Plan* list typically displays the latest releases of Cloud Volumes ONTAP.
. In the *Basics* tab, provide these details:
** *Subscription*: Select a subscription. The deployment will be linked to the subscription number.
** *Resource group*: Use an existing resource group or create a new one. Resource groups help in allocating all resources, such as disks and storage VMs, within a single group for a Cloud Volumes ONTAP system.
** *Region*: Select a region that supports Azure HA deployment in a single AZ. You see only the available regions on the list.
** *Size*: Select an storage VM size for the supported Premium SSD v2 Managed Disk.
** *Zone*: Select a zone for the region you selected. 
** *Admin Password*: Set a password. You use this admin password to log in to the system after the deployment.
** *Confirm Password*: Re-enter the same password for confirmation.
* In the *Network* tab, add a virtual network and a subnet, or select them from the lists.
+
[NOTE]
To comply with Microsoft Azure restrictions, you should create a new subnet when setting up a new virtual network. Likewise, if you choose an existing network, you should select an existing subnet.
+
* To select a predefined network security group, select *Yes*. Select *No* to assign a predefined Azure network security group with the necessary traffic rules. For more information, refer to link:reference-networking-azure.html#security-group-rules[Security group rules for Azure]. 
* In the *Advanced* tab confirm whether the two Azure features necessary for this deployment have been set. Refer to link:task-saz-feature.html[Enable an Azure feature for Cloud Volumes ONTAP single AZ deployments] and link:task-azure-high-availability-mode.html[Enable high-availability mode for Cloud Volumes ONTAP in Azure].
* You can define name and value pairs for the resources or resource groups in the *Tags* tab.
* In the *Review + create* tab, review the details and start the deployment.

.After you finish

Select the notification icon to view the progress of your deployment. After Cloud Volumes ONTAP is deployed, you can view the storage VM listed for operations.

Once accessible, use ONTAP System Manager or the ONTAP CLI to log in to the storage VM with the admin credentials that you set. Thereafter, you can create volumes, LUNs, or shares and start utilizing the storage capabilities of Cloud Volumes ONTAP.

== Troubleshoot deployment issues
Cloud Volumes ONTAP deployments made directly through the Azure marketplace do not include support from NetApp. If any issues arise during deployment, you can independently troubleshoot and resolve them.

.Steps
. On the Azure marketplace site, go to *Boot diagnostics > Serial log*.
. Download and investigate the serial logs.
. Consult the product documentation and knowledge base (KB) articles for troubleshooting.
** https://learn.microsoft.com/en-us/partner-center/[Azure marketplace documentation]
** https://www.netapp.com/support-and-training/documentation/[NetApp documentation]
** https://kb.netapp.com/[NetApp KB articles]

.Related links

Refer to the ONTAP documentation for more information about creating storage:

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html[Create volumes for NFS^]  
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html[Create LUNs for iSCSI^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html[Create shares for CIFS^]

== Discover the deployed systems in BlueXP
You can discover the Cloud Volumes ONTAP systems that you deployed using Azure marketplace direct deployment on BlueXP, and manage them as working environments. The BlueXP Connector discovers the systems, adds them as working environments, applies the necessary BlueXP licensing model, and unlocks the full capabilities of BlueXP for these systems.

For information about discovering and adding existing systems in BlueXP, refer to link:task-adding-systems.html[Add an existing Cloud Volumes ONTAP system to BlueXP].

When discovering the Cloud Volumes ONTAP systems deployed using Azure marketplace direct deployment, the BlueXP Connector performs these tasks:

* Discovers the free licenses of the deployed systems as a regular capacity-based Freemium licenses. For information about Freemium licenses, refer to link:/concept-licensing.html#packages[Capacity-based licensing packages].
* Retains the existing capabilities of the deployed systems, and adds the additional capabilities of BlueXP, such as data protection, data management, and security features.
* Provisions systems and activates accounts for tiering using FabricPool.
* Assigns the applicable cloud licenses on the instances.
* Converts the generic serial numbers of the nodes to unique serial numbers.
* Assigns new system tags on the resources as required.
* Converts the dynamic IP addresses of the storage VMs to static IP addresses.
* Replaces the installed licenses with the new licenses for NFS, CIFS (SMB), iSCSI, Autonomous Ransomware Protection (ARP), SnapLock, and SnapMirror.
* Enables AutoSupport for the deployed systems.
* Activates write-once-read-many (WORM) storage.
* Removes the unused cloud resources from the deployed systems.





