---
sidebar: sidebar
permalink: task-planning-your-config.html
keywords: license, disk, ebs, storage, size, write speed, volume usage, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported instances, instances, instances supported, supported ec2 instances, supported instance, aws outpost, outpost, outposts, deploy in outpost, deploy in aws outpost
summary: When you deploy Cloud Volumes ONTAP in AWS, you can choose a preconfigured system that matches your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.
---

= Plan your Cloud Volumes ONTAP configuration in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you deploy Cloud Volumes ONTAP in AWS, you can choose a preconfigured system that matches your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.

== Choose a Cloud Volumes ONTAP license

Several licensing options are available for Cloud Volumes ONTAP. Each option enables you to choose a consumption model that meets your needs.

* link:concept-licensing.html[Learn about licensing options for Cloud Volumes ONTAP]
* link:task-set-up-licensing-aws.html[Learn how to set up licensing]

== Choose a supported region

Cloud Volumes ONTAP is supported in most AWS regions. https://cloud.netapp.com/cloud-volumes-global-regions[View the full list of supported regions^].

Newer AWS regions must be enabled before you can create and manage resources in those regions. https://docs.aws.amazon.com/general/latest/gr/rande-manage.html[Learn how to enable a region^].

== Choose a supported instance

Cloud Volumes ONTAP supports several instance types, depending on the license type that you choose.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html[Supported configurations for Cloud Volumes ONTAP in AWS^]

== Understand storage limits

The raw capacity limit for a Cloud Volumes ONTAP system is tied to the license. Additional limits impact the size of aggregates and volumes. You should be aware of these limits as you plan your configuration.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-aws.html[Storage limits for Cloud Volumes ONTAP in AWS^]

== Size your system in AWS

Sizing your Cloud Volumes ONTAP system can help you meet requirements for performance and capacity. You should be aware of a few key points when choosing an instance type, disk type, and disk size:

Instance type::
* Match your workload requirements to the maximum throughput and IOPS for each EC2 instance type.
* If several users write to the system at the same time, choose an instance type that has enough CPUs to manage the requests.
* If you have an application that is mostly reads, then choose a system with enough RAM.
** https://aws.amazon.com/ec2/instance-types/[AWS Documentation: Amazon EC2 Instance Types^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html[AWS Documentation: Amazon EBS–Optimized Instances^]

EBS disk type::
At a high level, the differences between EBS disk types are as follows. To learn more about the use cases for EBS disks, refer to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html[AWS Documentation: EBS Volume Types^].

* _General Purpose SSD (gp3)_ disks are the lowest-cost SSDs that balance cost and performance for a broad range of workloads. Performance is defined in terms of IOPS and throughput. gp3 disks are supported with Cloud Volumes ONTAP 9.7 and later.
+
When you select a gp3 disk, BlueXP fills in default IOPS and throughput values that provide performance that is equivalent to a gp2 disk based on the selected disk size. You can increase the values to get better performance at a higher cost, but we do not support lower values because it can result in inferior performance. In short, stick with the default values or increase them. Don't lower them. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type[Learn more about gp3 disks and their performance^].
+
Note that Cloud Volumes ONTAP supports the Amazon EBS Elastic Volumes feature with gp3 disks. link:concept-aws-elastic-volumes.html[Learn more about Elastic Volumes support].

* _General Purpose SSD (gp2)_ disks balance cost and performance for a broad range of workloads. Performance is defined in terms of IOPS.

* _Provisioned IOPS SSD (io1)_ disks are for critical applications that require the highest performance at a higher cost.
+
Note that Cloud Volumes ONTAP supports the Amazon EBS Elastic Volumes feature with io1 disks. link:concept-aws-elastic-volumes.html[Learn more about Elastic Volumes support].

* _Throughput Optimized HDD (st1)_ disks are for frequently accessed workloads that require fast and consistent throughput at a lower price.
+
NOTE: Tiering data to object storage is not recommended when using Throughput Optimized HDDs (st1).

EBS disk size::
If you choose a configuration that doesn't support the link:concept-aws-elastic-volumes.html[Amazon EBS Elastic Volumes feature], then you need to choose an initial disk size when you launch a Cloud Volumes ONTAP system. After that, you can link:concept-storage-management.html[let BlueXP manage a system's capacity for you], but if you want to link:task-create-aggregates.html[create aggregates yourself], be aware of the following:

** All disks in an aggregate must be the same size.
** The performance of EBS disks is tied to disk size. The size determines the baseline IOPS and maximum burst duration for SSD disks and the baseline and burst throughput for HDD disks.
** Ultimately, you should choose the disk size that gives you the _sustained performance_ that you need.
** Even if you do choose larger disks (for example, six 4 TiB disks), you might not get all of the IOPS because the EC2 instance can reach its bandwidth limit.
+
For more details about EBS disk performance, refer to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html[AWS Documentation: EBS Volume Types^].
+
As noted above, choosing a disk size is not supported with Cloud Volumes ONTAP configurations that support the Amazon EBS Elastic Volumes feature. link:concept-aws-elastic-volumes.html[Learn more about Elastic Volumes support].

== View default system disks

In addition to the storage for user data, BlueXP also purchases cloud storage for Cloud Volumes ONTAP system data (boot data, root data, core data, and NVRAM). For planning purposes, it might help for you to review these details before you deploy Cloud Volumes ONTAP.

link:reference-default-configs.html#aws[View the default disks for Cloud Volumes ONTAP system data in AWS].

TIP: The Connector also requires a system disk. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html[View details about the Connector's default configuration^].

== Prepare to deploy Cloud Volumes ONTAP in an AWS Outpost

If you have an AWS Outpost, you can deploy Cloud Volumes ONTAP in that Outpost by selecting the Outpost VPC in the Working Environment wizard. The experience is the same as any other VPC that resides in AWS. Note that you will need to first deploy a Connector in your AWS Outpost.

There are a few limitations to point out:

* Only single node Cloud Volumes ONTAP systems are supported at this time
* The EC2 instances that you can use with Cloud Volumes ONTAP are limited to what's available in your Outpost
* Only General Purpose SSDs (gp2) are supported at this time

== Collect networking information

When you launch Cloud Volumes ONTAP in AWS, you need to specify details about your VPC network. You can use a worksheet to collect the information from your administrator.

=== Single node or HA pair in a single AZ

[cols=2*,options="header",cols="30,70"]
|===

| AWS information
| Your value

| Region |
| VPC |
| Subnet |
| Security group (if using your own) |

|===

=== HA pair in multiple AZs

[cols=2*,options="header",cols="30,70"]
|===

| AWS information
| Your value

| Region |
| VPC |
| Security group (if using your own) |
| Node 1 availability zone |
| Node 1 subnet |
| Node 2 availability zone |
| Node 2 subnet |
| Mediator availability zone |
| Mediator subnet |
| Key pair for the mediator |
| Floating IP address for cluster management port |
| Floating IP address for data on node 1 |
| Floating IP address for data on node 2 |
| Route tables for floating IP addresses |

|===

== Choose a write speed

BlueXP enables you to choose a write speed setting for Cloud Volumes ONTAP. Before you choose a write speed, you should understand the differences between the normal and high settings and risks and recommendations when using high write speed. link:concept-write-speed.html[Learn more about write speed].

== Choose a volume usage profile

ONTAP includes several storage efficiency features that can reduce the total amount of storage that you need. When you create a volume in BlueXP, you can choose a profile that enables these features or a profile that disables them. You should learn more about these features to help you decide which profile to use.

NetApp storage efficiency features provide the following benefits:

Thin provisioning:: Presents more logical storage to hosts or users than you actually have in your physical storage pool. Instead of preallocating storage space, storage space is allocated dynamically to each volume as data is written.

Deduplication:: Improves efficiency by locating identical blocks of data and replacing them with references to a single shared block. This technique reduces storage capacity requirements by eliminating redundant blocks of data that reside in the same volume.

Compression:: Reduces the physical capacity required to store data by compressing data within a volume on primary, secondary, and archive storage.
