---
sidebar: sidebar
permalink: task-connect-lun.html
keywords: lun, connect lun, iscsi lun, target iqn, iqn
summary: When you create an iSCSI volume, BlueXP automatically creates a LUN for you. We’ve made it simple by creating just one LUN per volume, so there's no management involved. After you create the volume, use the IQN to connect to the LUN from your hosts.
---

= Connect a LUN to a host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you create an iSCSI volume, BlueXP automatically creates a LUN for you. We’ve made it simple by creating just one LUN per volume, so there's no management involved. After you create the volume, use the IQN to connect to the LUN from your hosts.

Note the following:

* BlueXP's automatic capacity management doesn't apply to LUNs. When BlueXP creates a LUN, it disables the autogrow feature.

* You can create additional LUNs from System Manager or the CLI.

.Steps

. From the left navigation menu, select *Storage > Canvas*.

. On the Canvas page, double-click the Cloud Volumes ONTAP working environment on which you want to manage volumes.

. In the working environment, click the *Volumes* tab.

. On the Volumes tab, navigate to the desired volume title and then click *Manage volume* to access the Manage Volumes right-side panel.

. Click *Target iQN*.

. Click *Copy* to copy the iQN name.

. Set up an iSCSI connection from the host to the LUN.
+
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html[ONTAP 9 iSCSI express configuration for Red Hat Enterprise Linux: Starting the iSCSI sessions with the target^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html[ONTAP 9 iSCSI express configuration for Windows: Starting iSCSI sessions with the target^]
* https://docs.netapp.com/us-en/ontap-sanhost/[ONTAP SAN host configuration^]
