---
sidebar: sidebar
permalink: task-aws-key-management.html
keywords: aws, amazon, encryption, NVE, NetApp volume encryption, KMIP, kms, key manager service
summary: Utilize AWS's key management service for your third-party key management service.
---

= Manage keys with AWS Key Management Service
:icons: font
:hardbreaks:
:imagesdir: ../media/

[.lead]
You can use link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html[AWS's Key Management Service (KMS)^] to protect your ONTAP encryption keys in a Google Cloud Platform-deployed application.

Key management with the AWS KMS can be enabled with the CLI or the ONTAP REST API.

When using the KMS, be aware that by default a data SVM's LIF is used to communicate with the cloud key management endpoint. A node management network is used to communicate with AWS's authentication services. If the cluster network is not configured correctly, the cluster will not properly utilize the key management service.

.Before you begin
* Cloud Volumes ONTAP must be running version 9.12.0 or later
* You must have installed the Volume Encryption (VE) license and
* You must have installed the Multi-tenant Encryption Key Management (MTEKM) license installed.
* You must be a cluster or SVM administrator
* You must have an active AWS subscription

[NOTE]
You can only configure keys for a data SVM.

== Configuration

.AWS
. You must create a link:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant[grant^] for the AWS KMS key that will be used by the IAM role managing encryption. The IAM role must include a policy that allows the following operations: 
    * `DescribeKey`
    * `Encrypt`
    * `Decrypt`
    To create a grant, refer to link:https://docs.aws.amazon.com/kms/latest/developerguide/create-grant-overview.html[AWS documentation^].
. link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[Add a policy to the appropriate IAM role.^] The policy should support the `DescribeKey`, `Encrypt`, and `Decrypt` operations. 

.Cloud Volumes ONTAP
. Switch to your Cloud Volumes ONTAP environment.
. Switch to the advanced privilege level:
`set -privilege advanced`
. Enable the AWS key manager:
`security key-manager external aws enable -vserver _data_svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. When prompted, enter the secret key.
. Confirm the AWS KMS was configured correctly:
`security key-manager external aws show -vserver _svm_name_`

// BLUEXPDOC-10