---
sidebar: sidebar
permalink: task-planning-your-config-gcp.html
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances
summary: When you deploy Cloud Volumes ONTAP, you can choose a preconfigured system that matches your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.
---

= Plan your Cloud Volumes ONTAP configuration in Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you deploy Cloud Volumes ONTAP in Google Cloud, you can choose a preconfigured system that matches your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.

== Choose a Cloud Volumes ONTAP license

Several licensing options are available for Cloud Volumes ONTAP. Each option enables you to choose a consumption model that meets your needs.

* link:concept-licensing.html[Learn about licensing options for Cloud Volumes ONTAP]
* link:task-set-up-licensing-google.html[Learn how to set up licensing]

== Choose a supported region

Cloud Volumes ONTAP is supported in most Google Cloud regions. https://cloud.netapp.com/cloud-volumes-global-regions[View the full list of supported regions^].

== Choose a supported machine type

Cloud Volumes ONTAP supports several machine types, depending on the license type that you choose.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html[Supported configurations for Cloud Volumes ONTAP in GCP^]

== Understand storage limits

The raw capacity limit for a Cloud Volumes ONTAP system is tied to the license. Additional limits impact the size of aggregates and volumes. You should be aware of these limits as you plan your configuration.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html[Storage limits for Cloud Volumes ONTAP in GCP^]

== Size your system in GCP

Sizing your Cloud Volumes ONTAP system can help you meet requirements for performance and capacity. You should be aware of a few key points when choosing a machine type, disk type, and disk size:

Machine type::
Look at the supported machine types in the http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html[Cloud Volumes ONTAP Release Notes^] and then review details from Google about each supported machine type. Match your workload requirements to the number of vCPUs and memory for the machine type. Note that each CPU core increases networking performance.
+
Refer to the following for more details:
+
** https://cloud.google.com/compute/docs/machine-types#n1_machine_types[Google Cloud documentation: N1 standard machine types^]
** https://cloud.google.com/docs/compare/data-centers/networking#performance[Google Cloud documentation: Performance^]

GCP disk type::
When you create volumes for Cloud Volumes ONTAP, you need to choose the underlying cloud storage that Cloud Volumes ONTAP uses for a disk. The disk type can be any of the following:
+
* _Zonal SSD persistent disks_: SSD persistent disks are best for workloads that require high rates of random IOPS.
* _Zonal Balanced persistent disks_: These SSDs balance performance and cost by providing lower IOPS per GB.
* _Zonal Standard persistent disks_ : Standard persistent disks are economical and can handle sequential read/write operations.
+
For more details, see https://cloud.google.com/compute/docs/disks/#pdspecs[Google Cloud documentation: Zonal Persistent disks (Standard and SSD)^].

GCP disk size::
You need to choose an initial disk size when you deploy a Cloud Volumes ONTAP system. After that you can let BlueXP manage a system's capacity for you, but if you want to build aggregates yourself, be aware of the following:
+
* All disks in an aggregate must be the same size.
* Determine the space that you need, while taking performance into consideration.
* The performance of persistent disks scales automatically with disk size and the number of vCPUs available to the system.
+
Refer to the following for more details:
+
** https://cloud.google.com/compute/docs/disks/#pdspecs[Google Cloud documentation: Zonal Persistent disks (Standard and SSD)^]
** https://cloud.google.com/compute/docs/disks/performance[Google Cloud documentation: Optimizing Persistent Disk and Local SSD Performance^]

== View default system disks

In addition to the storage for user data, BlueXP also purchases cloud storage for Cloud Volumes ONTAP system data (boot data, root data, core data, and NVRAM). For planning purposes, it might help for you to review these details before you deploy Cloud Volumes ONTAP.

* link:reference-default-configs.html#google-cloud-single-node[View the default disks for Cloud Volumes ONTAP system data in Google Cloud].
* https://cloud.google.com/compute/quotas[Google Cloud docs: Resource quotas^]
+
Google Cloud Compute Engine enforces quotas on resource usage so you should ensure that you haven't reached your limit before you deploy Cloud Volumes ONTAP.

TIP: The Connector also requires a system disk. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html[View details about the Connector's default configuration^].

== Collect networking information

When you deploy Cloud Volumes ONTAP in GCP, you need to specify details about your virtual network. You can use a worksheet to collect the information from your administrator.

*Network information for a single-node system*

[cols=2*,options="header",cols="30,70"]
|===

| GCP information
| Your value

| Region |
| Zone |
| VPC network |
| Subnet |
| Firewall policy (if using your own) |

|===

*Network information for an HA pair in multiple zones*

[cols=2*,options="header",cols="30,70"]
|===

| GCP information
| Your value

| Region |
| Zone for Node 1 |
| Zone for Node 2 |
| Zone for the mediator |
| VPC-0 and subnet |
| VPC-1 and subnet |
| VPC-2 and subnet |
| VPC-3 and subnet |
| Firewall policy (if using your own) |

|===

*Network information for an HA pair in a single zone*

[cols=2*,options="header",cols="30,70"]
|===

| GCP information
| Your value

| Region |
| Zone |
| VPC-0 and subnet |
| VPC-1 and subnet |
| VPC-2 and subnet |
| VPC-3 and subnet |
| Firewall policy (if using your own) |

|===

== Choose a write speed

BlueXP enables you to choose a write speed setting for Cloud Volumes ONTAP, except for high availability (HA) pairs in Google Cloud. Before you choose a write speed, you should understand the differences between the normal and high settings and risks and recommendations when using high write speed. link:concept-write-speed.html[Learn more about write speed].

== Choose a volume usage profile

ONTAP includes several storage efficiency features that can reduce the total amount of storage that you need. When you create a volume in BlueXP, you can choose a profile that enables these features or a profile that disables them. You should learn more about these features to help you decide which profile to use.

NetApp storage efficiency features provide the following benefits:

Thin provisioning:: Presents more logical storage to hosts or users than you actually have in your physical storage pool. Instead of preallocating storage space, storage space is allocated dynamically to each volume as data is written.

Deduplication:: Improves efficiency by locating identical blocks of data and replacing them with references to a single shared block. This technique reduces storage capacity requirements by eliminating redundant blocks of data that reside in the same volume.

Compression:: Reduces the physical capacity required to store data by compressing data within a volume on primary, secondary, and archive storage.
