---
sidebar: sidebar
permalink: task-convert-node-capacity.html
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity
summary: The Event Management System collects and displays information about events that occur on  ONTAP systems. To receive event notifications, you can set event destinations and event routes for a particular event severity.
---

= Convert node-based licenses to capacity based
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After the end of availability (EOA) of your node-based licenses, you should transition to capacity-based licensing. For annual or longer-term commitments, NetApp recommends that you contact the support team prior to the EOA date or license expiry date to ensure a seamless transition. If you have a PAYGO subscription, you should initiate the transition to capacity-based licensing, because there will be no automatic conversion, and you will be unable to receive support from NetApp.

.About this task

* The transition from node-based to capacity-based licensing model is done online and in-place that does not require any data migration or provisioning of additional cloud resources.
* It is a non-disruptive operation, and no service disruption or application downtime occurs.
* Account and application data in your Cloud Volumes ONTAP system remains intact.
* The underlying cloud resources remain unaffected post conversion.
* Support for all CVO deployment types, such as single node, high availability (HA) in single availability zone (AZ), HA in multiple AZ, BYOL, and PAYGO.
* The conversion is supported for all cloud providers, AWS, Azure, and Google Cloud.
* Post conversion, the serial number of the node-based license will be replaced by a capacity-based format.
* When you transition to the capacity-based model, your data continues to be retained in the same location as the node-based licensing. This approach guarantees no disruption in data placement, and upholds data sovereignty principles throughout the transition.

.Before your begin

* You should have an NSS account with customer access or administrator access.
* Your NSS account should be registered with the BlueXP user credentials.
* The working environment should be linked to the NSS account with customer access or administrator access.
* You should have a valid capacity-based license or marketplace subscription.
* A capacity-based license should be available in the BlueXP account. This license can be a marketplace subscription or a BYOL/private offer package in the Digital Wallet.
* Understand the following criteria before selecting a destination package:
** If the account has a capacity-based BYOL license, the destination package selected should align with the account's BYOL capacity-based licenses:  
*** When `Professional` is selected as the destination package, the account should have a BYOL license with a Professional package:  
***	When `Essentials` is selected as the destination package, the account should have a BYOL license with the Essentials package.  
*** When `Optimized` is selected as the destination package, the account should have a BYOL license with the Optimized package.  
** If the destination package does not align with the account's BYOL license availability, it implies that the capacity license might not include the selected package. In this case, you will be charged through your marketplace subscription.
** If there is no capacity-based BYOL license but only marketplace subscription, you should ensure that the selected package is included in your capacity-based marketplace subscription.
** If there is not enough capacity in your existing capacity-based license, and if you have a marketplace subscription to charge for the additional capacity usage, you will be charged for the additional capacity through your marketplace subscription.
** If there is not enough capacity in your existing capacity-based license, and you don't have a marketplace subscription to charge for the additional capacity usage, the conversion cannot occur. You should add a marketplace subscription to charge the additional capacity or extend the available capacity to your current license.
** If the destination package does not align with the account's BYOL license availability and also if there is not enough capacity in your existing capacity-based license, then you will be charged through your marketplace subscription.


[NOTE]
If any of these criteria is not fulfilled, the license conversion does not happen. In specific cases, the license might be converted, but cannot be used. Click the information icon to view the appropriate messaging and identify the issues to take corrective actions.

.Steps

. On the Canvas page, double-click the name of the working environment for which you want to modify the license type.
. On the Overview tab, click the Features panel.
. Check the pencil icon next to *Charging method*. If the charging method for your system is `Node Based`, you need to convert it to by-capacity charging. The icon is disabled if your Cloud Volumes ONTAP system has an existing capacity-based license. 
. On the *Convert Node-based licenses to Capacity-based* screen, verify the working environment name and source license details.
. Select the destination package for converting the existing license:
ifdef::aws[]
ifdef::azure[]
ifdef::gcp[]
** Essential. The default value is `Essential`.
** Professional
endif::aws[]
** Optimized
endif::azure[]
endif::gcp[]
. If you have a BYOL subscription, you can select the checkbox to delete the node-based license post conversion. If you have a marketplace subscription, this option is unavailable.
. Select the check box to confirm that you understand the implications of the change, and then click *Proceed*.

.After you finish
View the new license serial number and verify the changes in Digital Wallet.

