---
sidebar: sidebar
permalink: task-managing-svms-gcp.html
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver
summary: A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an SVM or a vserver. Cloud Volumes ONTAP is configured with one storage VM by default, but some configurations support additional storage VMs.
---

= Create data-serving storage VMs for Cloud Volumes ONTAP in Google Cloud
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an _SVM_ or a _vserver_. Cloud Volumes ONTAP is configured with one storage VM by default, but some configurations support additional storage VMs.

== Supported number of storage VMs

Multiple storage VMs are supported with specific Cloud Volumes ONTAP configurations in Google Cloud starting with the 9.11.1 release. Go to the https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html[Cloud Volumes ONTAP Release Notes^] to verify the supported number of storage VMs for your version of Cloud Volumes ONTAP.

All other Cloud Volumes ONTAP configurations support one data-serving storage VM and one destination storage VM used for disaster recovery. You can activate the destination storage VM for data access if there's an outage on the source storage VM.

== Required Google Cloud permissions

Starting with the 3.9.19 release, the Connector requires the following permissions to create and manage storage VMs for Cloud Volumes ONTAP HA pairs:

[source,yaml]
- compute.instanceGroups.get
- compute.addresses.get

These permissions are included in https://mysupport.netapp.com/site/info/cloud-manager-policies[the policies provided by NetApp^]

The permissions are not required for single node systems.

== Create a storage VM

You can create a storage VM on a single node system or on an HA pair. Note that you musts use the Cloud Manager API to create a storage VM on an HA pair.

=== Single node system

These steps create a new storage VM on a single node system. One private IP address is required to create a NAS LIF and another optional private IP address is needed if you want to create a management LIF.

.Steps

. https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address#reservenewip[Reserve one or two static internal IP addresses^].
+
You need one IP address for a data LIF and another optional IP address if you want to create a management LIF on the storage VM.

. Create the storage VM and a route to the storage VM.
+
[source,cli]
vserver create -rootvolume-security-style unix -rootvolume root_svm_2 -snapshot-policy default -vserver svm_2 -aggregate aggr1
+
[source,cli]
network route create -destination 0.0.0.0/0 -vserver svm_2 -gateway subnet_gateway

. Create a data LIF.
+
// start tabbed area

[role="tabbed-block"]
====

.iSCSI
--
[source,cli]
network interface create -vserver <svm-name> -home-port e0a -address <iscsi-ip-address> -lif <lif-name> -home-node <name-of-node1> -data-protocol iscsi
--

.NFS or SMB
--
[source,cli]
network interface create -vserver <svm-name> -lif <lif-name> -role data -data-protocol cifs,nfs -address <nfs--ip-address> -netmask-length <length> -home-node <name-of-node1> -status-admin up -failover-policy disabled -firewall-policy data -home-port e0a -auto-revert true -failover-group Default
--

====

// end tabbed area

. Optional: Create a storage VM management LIF.
+
[source,cli]
network interface create -auto-revert true -vserver svm_2 -service-policy default-management -home-port e0a -address private_ip_y -netmask node1Mask -lif ip_svm_mgmt_2 -home-node cvo-node
+
Where _private_ip_y_ is another unused secondary private IP on e0a.

. Assign one or more aggregates to the storage VM.
+
[source,cli]
vserver add-aggregates -vserver svm_2 -aggregates aggr1,aggr2
+
This step is required because the new storage VM needs access to at least one aggregate before you can create volumes on the storage VM.

=== HA pair

You must use the Cloud Manager API to create a storage VM on a Cloud Volumes ONTAP system in Google Cloud. Using the API (and not System Manager or the CLI) is required because Cloud Manager configures the storage VM with the required LIF services, as well as an iSCSI LIF for an HA pair that's required for outbound SMB/CIFS communication.

.Steps

. Use the following API call to create a storage VM:
+
`POST /occm/api/gcp/ha/working-environments/{WE_ID}/svm/`
+
The request body should include the following:
+
[source,json]
{ "svmName": "myNewSvm1" }

== Manage storage VMs on HA pairs

The Cloud Manager API also supports renaming and deleting storage VMs.

=== Rename a storage VM

If needed, you can change the name of a storage VM at any time.

.Steps

. Use the following API call to rename a storage VM:
+
`PUT /occm/api/gcp/ha/working-environments/{WE_ID}/svm`
+
The request body should include the following:
+
[source,json]
{
"svmNewName": "newSvmName",
"svmName": "oldSvmName"
}

=== Delete a storage VM

If you no longer need a storage VM, you can delete it from Cloud Volumes ONTAP.

.Steps

. Use the following API call to delete a storage VM:
+
`DELETE /occm/api/gcp/ha/working-environments/{WE_ID}/svm/{SVM_NAME}`
