---
sidebar: sidebar
permalink: task-managing-svms-azure.html
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported
summary: A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an SVM or a vserver. Cloud Volumes ONTAP is configured with one storage VM by default, but some configurations support additional storage VMs.
---

= Create data-serving storage VMs for Cloud Volumes ONTAP in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an _SVM_ or a _vserver_. Cloud Volumes ONTAP is configured with one storage VM by default, but you can create additional storage VMs when running Cloud Volumes ONTAP in Azure.

To create and manage additional data-serving storage VMs on Azure, you should use the APIs provided by BlueXP. This is because the APIs automate the process of creating the storage VMs and configuring the required network interfaces. When creating the storage VMs, BlueXP configures the required LIF services, as well as an iSCSI LIF that's required for outbound SMB/CIFS communications from the storage VM.

NOTE: To perform additional NIC-related tasks, you can assign a network contributor role or custom role with appropriate permissions in Azure. For more information on these NIC-related permissions, refer to the https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface?tabs=azure-portal#permissions[Microsoft Azure documentation^].

== Supported number of storage VMs

Beginning with Cloud Volumes ONTAP 9.9.0, multiple storage VMs are supported with specific configurations, based on the license types. Refer to the https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html[Cloud Volumes ONTAP Release Notes^] to verify the supported number of storage VMs for your version of Cloud Volumes ONTAP.

All other Cloud Volumes ONTAP configurations support one data-serving storage VM and one destination storage VM used for disaster recovery. You can activate the destination storage VM for data access if there's an outage on the source storage VM.

.Before you begin

The Connector requires specific permissions to create and manage storage VMs for Cloud Volumes ONTAP. The required permissions are included in https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html[the policies provided by NetApp^].

== Create a storage VM
If your configuration supports it, you can create multiple storage VMs on a single node system or in a high-availability (HA) configuration by using the BlueXP APIs.

.About this task

When you create storage VMs using the APIs, along with configuring the required network interfaces, BlueXP also modifies the `default-data-files` policies on the data storage VMs by removing the following services from the NAS data LIF and adding them to the iSCSI data LIF that's used for outbound management connections:

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`

=== Single node system

This step creates a storage VM on a single node system. 

.Steps

. Use the following API call to create a storage VM:
+
`POST /occm/api/azure/vsa/working-environments/{workingEnvironmentId}/svm`
+
The request body should include the following:
+
[source,json]
{ "svmName": "myNewSvm1" 
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}


=== HA pair
This step creates a storage VM in an Azure HA configuration.

.Steps

. Use the following API call to create a storage VM:
+
`POST /occm/api/azure/ha/working-environments/{workingEnvironmentId}/svm`
+
The request body should include the following:
+
[source,json]
{ "svmName": "NewSvmName" 
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}


== Manage storage VMs on single node systems and HA pairs

Using the BlueXP APIs, you can rename and delete storage VMs in both single node and HA configurations.

=== Rename a storage VM

To rename a storage VM, you should provide the names of the existing storage VM and the new storage VM as parameters.

.Steps

* Use the following API call to rename a storage VM on a single node system:
+
`PUT /azure/vsa/working-environments/{workingEnvironmentId}/svm`
+
The request body should include the following:
+
[source,json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* Use the following API call to rename a storage VM in an HA configuration:
+
`PUT /azure/ha/working-environments/{workingEnvironmentId}/svm`
+
The request body should include the following:
+
[source,json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----

=== Delete a storage VM

In a single node or HA configuration, you have the ability to remove a storage VM if it doesn't have any active volumes.

.Steps

* Use the following API call to delete a storage VM on a single node system:
+
`DELETE /occm/api/azure/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`
*  Use the following API call to delete a storage VM in an HA configuration:
+
`DELETE /occm/api/azure/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`